
ll_modol.o: epoll_modol.cc epoll_modol.h IO_modol.h NonCopyable.h \
 RIO.h
poll_modol.o: poll_modol.cc poll_modol.h IO_modol.h NonCopyable.h RIO.h
RIO.o: RIO.cc RIO.h NonCopyable.h
select_modol.o: select_modol.cc select_modol.h IO_modol.h NonCopyable.h \
 RIO.h
server.o: server.cc RIO.h NonCopyable.h epoll_modol.h IO_modol.h \
 poll_modol.h select_modol.h
